os: osx
osx_image: xcode12.2
language: swift

cache:
  bundler: true 
  cocoapods: true

before_install:
  - gem install cocoapods
  - pod --version
  - pod repo update
install:  
  - bundle install
  - cd Example; pod install; cd ..;

env:
  global:
    # COCOAPODS_TRUNK_TOKEN - access token to deploy to cocoapods.

jobs:
  include:
  - stage: tests
    script:
      - pod lib lint --allow-warnings Wendy.podspec
      - bundle exec fastlane scan
  - stage: pull-request
    script: 
      - bundle exec fastlane scan 
      - bundle exec danger --fail-on-errors=true
  - stage: deploy
    script: pod trunk push --allow-warnings

stages:
  - name: tests
    if: type IN (pull_request, push) AND tag IS blank
  - name: pull-request
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present
